# Site settings
title: JDOSTech Blog
SEOTitle: Jingdong Datacenter Operating System 的博客 | JDOSTech Blog
header-img: img/home-bg.jpg
email: JDOSTech@gmail.com
description: "Jingdong Datacenter Operating System, 关于数据中心、基础设施、平台的技术 | 这里是 JDOSTech 的团队技术博客。"
keyword: "JDOS, JDOSTech, Jingdong Datacenter Operating System"
url: "https://JDOSTech.github.io"
baseurl: ""



# SNS settings
RSS: false
#weibo_username:     huxpro
#zhihu_username:     huxpro
github_username:    JDOSTech
#twitter_username:  huxpro
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: jdostech
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id:
# Google Analytics
#ga_track_id: ''            # Format: UA-xxxxxx-xx
#ga_domain:



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "踏实做事，匠心品格。"
sidebar-avatar: /img/avatar-jdos.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "李旦的博客",
        href: "http://danielfresh.github.io/"
    }

]
